# render.yaml - The final and simplified version

services:
  # This single web service runs everything
  - name: yeab-game-zone
    type: web
    env: python
    pythonVersion: '3.11' # Use a specific, modern Python version
    buildCommand: "pip install -r requirements.txt"
    # This start command points to the 'app' object in the root 'app.py'
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yeab-game-zone-db
          property: connectionString # We get the standard string and fix it in Python
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHAPA_API_KEY
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: yeab-game-zone
          property: url

  # The database service definition
  - name: yeab-game-zone-db
    type: psql
    version: "14"