# render.yaml - The Final and Correct Version

services:
  # This single web service runs both the FastAPI backend and the Telegram bot logic
  - name: yeab-game-zone
    type: web
    env: python
    # Ensure your Python version matches what you develop with
    pythonVersion: '3.11' # Or your specific Python version
    buildCommand: "pip install -r requirements.txt"
    # This start command points to the 'app' object in the root 'app.py'
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yeab-game-zone-db
          property: connectionString
          # This option is CRITICAL to prevent the async driver error
          options:
            protocol: "postgresql+asyncpg"
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Keep your token secret
      - key: CHAPA_API_KEY
        sync: false # Keep your API key secret
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: yeab-game-zone # Must match this service's name
          property: url

  # The database service definition
  - name: yeab-game-zone-db
    type: psql
    version: "14"