# render.yaml - The Final, Production-Ready Version

services:
  # This single web service runs the entire application
  - name: yeab-game-zone
    type: web
    env: python
    pythonVersion: '3.11' # Using a modern, specific Python version is good practice
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app"
    
    # =======================================================================
    # --- THIS IS THE RECOMMENDED IMPROVEMENT: The Health Check Path ---
    # This tells Render to check the "/" endpoint to confirm the app is running.
    # =======================================================================
    healthCheckPath: /
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yeab-game-zone-db
          property: connectionString # The standard string is fine; our Python code now handles the driver
      - key: TELEGRAM_BOT_TOKEN
        sync: false # You must set this value in the Render dashboard's Environment tab
      - key: CHAPA_API_KEY
        sync: false # You must set this value in the Render dashboard's Environment tab
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: yeab-game-zone # Must match this service's name
          property: url

  # The database service definition remains the same
  - name: yeab-game-zone-db
    type: psql
    version: "14"